spring:
  application:
    name: "Search Engine Backend"
  datasource:
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: "SELECT 1"
      pool-name: SearchEngineDBPool
      leak-detection-threshold: 5000
cache:
  memory:
    index:
      size: 20
      ttl: 30
    doc:
      size: 100
      ttl: 30
search-engine:
  title-weight: 0.7
  body-weight: 0.3
  cosine-weight: 0.7
  bigram-weight: 0.3
  relevance-weight: 0.9
  page-rank-weight: 0.1
  min-score-threshold: 0
  max-result-count: 50